### PR TITLE
Create install-apache

### PR DESCRIPTION
**Pull request by wyatt-herkamp**
how to install minepos in apache2

### CODE REVIEW

**Review by AndrewAubury — CHANGES_REQUESTED** [review]
Pleace fix the Typos "THe" and make sure it will work with "Read the Docs"

**Comment by wyatt-herkamp** [comment]
Quick question how do I check if it will work with Read The Docs?

**Comment by wyatt-herkamp** [comment]
https://documentation-tux.readthedocs.io/en/latest/#installation-apache2
Got it working :)

**Review by AndrewAubury — COMMENTED** [review]
Thank you

**Pull request merged**
